Corected port

diff --git a/pacman/healthcheck b/pacman/healthcheck
--- a/pacman/healthcheck
+++ b/pacman/healthcheck
@@ -7,9 +7,9 @@ if [ -z "$CHECK_TASK_PID" ]; then
 fi
 
 # Check to see if nginx is responding
-curl --fail http://localhost:7778/health?source=docker || exit 1
+curl --fail http://localhost:8888/health?source=docker || exit 1
 
-# Check to see if flathub cache can be accessed
-curl --fail --insecure http://localhost:7778/ping?source=nginx-flathub.local\&should_bypass_cache=true || exit 1
+## Check to see if pacman cache can be accessed
+#curl --fail --insecure http://localhost:8888/ping?source=nginx-pacman.local\&should_bypass_cache=true || exit 1
 
 exit 0
